//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpCrudFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email { get; set; }
        public int IdDepartamento { get; set; }
        public string Puesto { get; set; }
        public decimal Sueldo { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public bool Activo { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
